version: '3.8'

services:
  dma-server:
    image: node:20-alpine
    container_name: dma-server
    working_dir: /app
    volumes:
      - ./server:/app
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "9001:9001"
    environment:
      - PORT=9001
    command: sh -c "apk add --no-cache docker-cli docker-cli-compose && npm install && node --watch index.js"
    restart: unless-stopped

  dma-client:
    image: node:20-alpine
    container_name: dma-client
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - "9000:3000"
    environment:
      - API_TARGET=http://dma-server:9001
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - dma-server
    restart: unless-stopped
